name: BlockGPT
version: '0.1.00-BETA'
main: games.jvrcruz.blockgpt.BlockGPT
api-version: '1.20'
author: jvrcruz
description: A plugin that integrates Minecraft with Google Gemini AI and provides an interface for developers to interact with the AI inside of the game.
commands:
  ask:
    description: Ask Gemini a question
    usage: /ask <message>
    permission: blockgpt.ask
  reply:
    description: Reply to a Gemini response
    usage: /reply <message>
    permission: blockgpt.ask